name: Terraform ci/cd 

on:
    push:
        branches:
        - main

jobs:
    Docker_Image_build_and_push:
        name: Docker build and push
        runs-on: ubuntu-latest
        environment: Docker

        steps:
            - name: Checkout the code
              uses: actions/checkout@v3

            - name: Docker login
              uses: docker/login-action@v2
              with:
                username: ${{secrets.DOCKER_USERNAME }}
                password: ${{secrets.DOCKER_PASSWORD}}
                
            # - name: Build Docker image
            #   run: |
            #     docker build -t pratyaksh0106/ALBwithASG:latest .
            
            # - name: Push Docker image
            #   run: |
            #     docker push pratyaksh0106/ALBwithASG:latest

    
    Terraform_code_apply:
        name: AWS resources build
        runs-on: ubuntu-latest   
        environment: Dev
        needs: Docker_Image_build_and_push

        steps:
            - name: Checkout the code
              uses: actions/checkout@v3

            - name: AWS setup
              uses: aws-actions/configure-aws-credentials@v3
              with:
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: terraform setup
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.5.7

            - name: initialize terraform
              run: terraform init
            - name: validation
              run: terraform validate
            - name: terraform plan -out=tfplan
              run: terraform plan
            - name: terraform apply
              run: terraform apply -auto-approve -out=tfplan  
            - name: destroy
              uses: terraform destroy -auto-approve-out=tfplan