name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  Docker_Image_build_and_push:
    name: Docker build and push
    runs-on: ubuntu-latest
    environment: Docker

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t pratyaksh0106/albwithasg:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push pratyaksh0106/albwithasg:${{ github.sha }}

  Terraform_code_apply:
    name: AWS resources build
    runs-on: ubuntu-latest
    environment: Dev
    needs: Docker_Image_build_and_push

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: AWS setup
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Correct the region here

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -out=tfplan

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan

      - name: Terraform destroy
        run: terraform destroy -auto-approve
